version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci(github-actions)
    groups:
      github-actions:
        update-types: [minor, patch]
    ignore:
      - dependency-name: checkmarx/kics-github-action
        versions: [2.1.8]
