repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v4.1.0
    hooks:
      - id: validate_manifest
        name: pre-commit autoupdate
        entry: pre-commit autoupdate
        files: ""
        pass_filenames: false
