["{{ .zim_home }}"]
type = "archive"
url = "https://github.com/zimfw/zimfw/archive/master.tar.gz"
stripComponents = 1
refreshPeriod = "168h"

[".config/git/alias"]
type = "file"
url = "https://raw.githubusercontent.com/GitAlias/gitalias/refs/heads/main/gitalias.txt"
refreshPeriod = "168h"

[".config/git/ignore"]
type = "file"
url = "https://raw.githubusercontent.com/github/gitignore/refs/heads/main/Global/Linux.gitignore"
refreshPeriod = "168h"
