[".config/git/alias"]
  type = "file"
  url = "https://raw.githubusercontent.com/GitAlias/gitalias/refs/heads/main/gitalias.txt"
  refreshPeriod = "168h"

[".config/git/ignore"]
  type = "file"
{{- if eq .chezmoi.os "darwin" }}
  url = "https://raw.githubusercontent.com/github/gitignore/refs/heads/main/Global/macOS.gitignore"
{{- else if eq .chezmoi.os "linux" }}
  url = "https://raw.githubusercontent.com/github/gitignore/refs/heads/main/Global/Linux.gitignore"
{{- else if eq .chezmoi.os "windows" }}
  url = "https://raw.githubusercontent.com/github/gitignore/refs/heads/main/Global/Windows.gitignore"
{{- end }}
  refreshPeriod = "168h"
