#!/usr/bin/env zsh

# profiling setup

[[ -v ZPROF ]] && zmodload zsh/zprof || true

if [[ -v SOURCETRACE ]]; then
    PS4='%D{%S.%.} %N:%i> '
    setopt sourcetrace prompt_subst
fi

if [[ -v XTRACE ]]; then
    PS4='%D{%S.%.} %N:%i> '
    exec 3>&2 2>/tmp/zsh_trace.$$
    setopt xtrace prompt_subst
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-${HOME}/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-${HOME}/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Start configuration added by Zim install
#
# User configuration sourced by interactive shells
#

source "${ZDOTDIR}/pre.zsh"

# ------------------
# Initialize modules
# ------------------

ZIM_HOME=${XDG_CONFIG_HOME:-${HOME}}/zim
# Download zimfw plugin manager if missing.
if [[ ! -e "${ZIM_HOME}/zimfw.zsh" ]]; then
  zimfw_url=https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
  curl -fsSL --create-dirs -o "${ZIM_HOME}/zimfw.zsh" "${zimfw_url}"
fi
# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! "${ZIM_HOME}/init.zsh" -nt "${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc}" ]]; then
  source "${ZIM_HOME}/zimfw.zsh" init -q
fi

# Initialize modules.
source "${ZIM_HOME}/init.zsh"

# ------------------------------
# Post-init module configuration
# ------------------------------

zsh-defer -12 source "${ZDOTDIR}/post.zsh"

# To customize prompt, run `p10k configure` or edit ${ZDOTDIR}/.p10k.zsh.
[[ ! -f ${ZDOTDIR}/.p10k.zsh ]] || source "${ZDOTDIR}/.p10k.zsh"

# profiling tear down

[[ -v SOURCETRACE ]] && unsetopt sourcetrace || true

if [[ -v XTRACE ]]; then
  unsetopt xtrace
  exec 2>&3 3>&-
  echo "zsh xtrace: /tmp/zsh_trace.$$"
fi

[[ -v ZPROF ]] && zprof || true
