#!/usr/bin/env zsh
[[ -v sourced_zdotdir_zshenv ]] && return || true
sourced_zdotdir_zshenv=1

setopt EXTENDED_GLOB

skip_global_compinit=1

home_zshenv=${HOME}/.zshenv
[[ -f "${home_zshenv}" ]] && source "${home_zshenv}" || true

typeset -U path

for profile in ${(z)NIX_PROFILES}; do
  path=(${profile}/bin ${path})
done

path=(${HOME}{/.local,}/{,s}bin(FN) ${^path}(N))

export XDG_CACHE_HOME=${HOME}/.cache
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_STATE_HOME=${HOME}/.local/state
export ZDOTDIR=${XDG_CONFIG_HOME}/zsh
