on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      # - uses: DeterminateSystems/flake-checker-action@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          determinate: true
          trust-runner-user: true
          extra-conf: |
            trusted-users = root runner
      # - uses: cachix/cachix-action@v15
      #   with:
      #     name: nix-community
      # - uses: cachix/cachix-action@v15
      #   with:
      #     name: cachix
      - uses: astro/deadnix-action@main
      - run: nix flake check
      - run: nix fmt
