on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      # - uses: DeterminateSystems/flake-checker-action@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ github.token }}
      - uses: cachix/cachix-action@v15
        with:
          name: cachix
          extraPullNames: nix-community,nixpkgs-unfree
      - run: nix flake check
      - run: nix fmt
