name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  nix-check:
    permissions:
      actions: write
      contents: read

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # - uses: DeterminateSystems/flake-checker-action@v4

      # - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      #   with:
      #     determinate: true
      # - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
      #   with:
      #     github_access_token: ${{ github.token }}
      - uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703 # v30

      - uses: nix-community/cache-nix-action@c448f065ba14308da81de769632ca67a3ce67cf5 # v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          gc-max-store-size-linux: 1073741824
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}-
          # created more than this number of seconds ago relative to the start of the `Post Restore` phase
          purge-created: 0
          # except the version with the `primary-key`, if it exists
          purge-primary-key: never

      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: cachix
          extraPullNames: nix-community,nixpkgs-unfree

      - run: nix flake check

      - uses: astro/deadnix-action@ee2dbf0e5d720af59156d620d843fe4964d794ca
        with:
          create_pr: false

      - run: nix fmt

      - id: verify-changed-files
        uses: tj-actions/verify-changed-files@6ed7632824d235029086612d4330d659005af687 # v20
        with:
          fail-if-changed: true

  context:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Dump GitHub script context
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: console.log(JSON.stringify(context, null, 2))

      - name: Dump GitHub context
        run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Dump job context
        run: echo "${JOB_CONTEXT}"
        env:
          JOB_CONTEXT: ${{ toJson(job) }}

      - name: Dump steps context
        run: echo "${STEPS_CONTEXT}"
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}

      - name: Dump runner context
        run: echo "${RUNNER_CONTEXT}"
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}

      - name: Dump strategy context
        run: echo "${STRATEGY_CONTEXT}"
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}

      - name: Dump matrix context
        run: echo "${MATRIX_CONTEXT}"
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

      - name: Dump environment variables
        run: ${{ (runner.os == 'Windows') && 'gci env:' || 'env | sort' }}
