name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  nix-check:
    permissions:
      actions: write
      contents: read

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12

      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34

      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: cachix
          extraPullNames: nix-community,nixpkgs-unfree

      - run: nix flake check

      - uses: astro/deadnix-action@e6b9bbace580c30ff1e1bfa4d7e22b1c1d1ce56e
        with:
          create_pr: false

      - run: nix fmt

      - run: |
          changed_files=$(git ls-files --modified --others --directory --no-empty-directory --exclude-standard)
          if [ -n "${changed_files}" ]; then
            echo "Found uncommitted changes: ${changed_files}"
            exit 1
          fi
          echo "No changes found."

  chezmoi:
    permissions:
      contents: read

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - run: ./install.sh
        shell: zsh {0}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - run: |
          echo ${ZSH_NAME} ${ZSH_VERSION}
          echo path: ${path}
          echo fpath: ${fpath}
          echo setopt: $(setopt)
          echo unsetopt: $(unsetopt)
        shell: zsh {0}

  context:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Dump GitHub script context
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: console.log(JSON.stringify(context, null, 2))

      - name: Dump GitHub context
        run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Dump job context
        run: echo "${JOB_CONTEXT}"
        env:
          JOB_CONTEXT: ${{ toJson(job) }}

      - name: Dump steps context
        run: echo "${STEPS_CONTEXT}"
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}

      - name: Dump runner context
        run: echo "${RUNNER_CONTEXT}"
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}

      - name: Dump strategy context
        run: echo "${STRATEGY_CONTEXT}"
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}

      - name: Dump matrix context
        run: echo "${MATRIX_CONTEXT}"
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}

      - name: Dump environment variables
        run: ${{ (runner.os == 'Windows') && 'gci env:' || 'env | sort' }}
