name: dependabot
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

permissions: {}

jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v2
        id: metadata

      - name: log metadata
        env:
          DEPENDABOT_METADATA: ${{ toJson(steps.metadata.outputs) }}
        run: echo "${DEPENDABOT_METADATA}"

      - name: automerge
        if: ${{ !contains(steps.metadata.outputs.update-type, 'major' ) }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge --auto --squash "${PR_NUMBER}"
