name: megalinter
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
permissions: {}
jobs:
  megalinter:
    permissions:
      contents: write
      pull-requests: write
      security-events: write
      statuses: write
    uses: yxtay/.github/.github/workflows/megalinter.yml@e43859b1f5ecd4ba803c791058a83cd5e1e9422b # main
    with:
      run-ci_light: false
      run-documentation: true
