on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Nix Checks
    runs-on: macos-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v3
      # - uses: DeterminateSystems/flake-checker-action@v4
      - uses: DeterminateSystems/nix-installer-action@v3
        with:
          determinate: true
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: astro/deadnix-action@main
      - run: nix flake check
      - run: nix fmt
