name: pr
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
permissions: {}
jobs:
  pr:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: yxtay/.github/.github/workflows/pr.yml@e43859b1f5ecd4ba803c791058a83cd5e1e9422b # main
